### ISSUE TITLE
Updated version

### ISSUE THREAD

**Issue by srvanderplas** [pommevilla/quarto-render#19]
This is still using Quarto 0.2.xxx; we're now on 0.9.494 and a number of new features have been added to quarto. I understand the desire to ensure stability, but it might be good to update this action now that quarto is being publicized. 

In addition, there are several features in the quarto documentation (advanced figure alignment/formatting, comments, etc.) that are not supported in this older version of quarto.

**Comment by pommevilla** [comment]
Hi there, sorry for the late response. I've updated the Quarto version to the most recent version at this time (1.2.269). However, this Github action is no longer supported as there are now official [Quarto Github actions](https://github.com/quarto-dev/quarto-actions) maintained by the Quarto development team.
